oof

diff --git a/.github/workflows/python-test.yml b/.github/workflows/python-test.yml
--- a/.github/workflows/python-test.yml
+++ b/.github/workflows/python-test.yml
@@ -50,24 +50,24 @@ jobs:
         name: coverage-report
         path: coverage.xml
 
-    - name: Download Code Climate test reporter
-      run: |
-        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
-        chmod +x ./cc-test-reporter
-        
-        # Verify download was successful
-        if [ ! -s ./cc-test-reporter ]; then
-          echo "Download failed or file is empty."
-          exit 1
-        fi
-        echo "Code Climate test reporter downloaded successfully."
+      - name: Download Code Climate test reporter
+        run: |
+          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
+          chmod +x ./cc-test-reporter
+          
+          # Verify download was successful
+          if [ ! -s ./cc-test-reporter ]; then
+            echo "Download failed or file is empty."
+            exit 1
+          fi
+          echo "Code Climate test reporter downloaded successfully."
 
-    - name: Upload coverage to Code Climate
-      env:
-        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
-      run: |
-        ./cc-test-reporter before-build
-        actions/download-artifact@v3
-        ./cc-test-reporter format-coverage -t coverage.py -o coverage/codeclimate.json
-        ./cc-test-reporter sum-coverage -o coverage/codeclimate.json coverage.xml
-        ./cc-test-reporter upload-coverage    
+      - name: Upload coverage to Code Climate
+        env:
+          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
+        run: |
+          ./cc-test-reporter before-build
+          actions/download-artifact@v3
+          ./cc-test-reporter format-coverage -t coverage.py -o coverage/codeclimate.json
+          ./cc-test-reporter sum-coverage -o coverage/codeclimate.json coverage.xml
+          ./cc-test-reporter upload-coverage    
