refactor

diff --git a/.github/workflows/python-test.yml b/.github/workflows/python-test.yml
--- a/.github/workflows/python-test.yml
+++ b/.github/workflows/python-test.yml
@@ -33,10 +33,36 @@ jobs:
           pip install -r requirements-dev.txt
           pip install coverage
 
+       - name: Download Code Climate test reporter
+        run: |
+          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
+          chmod +x ./cc-test-reporter
+          
+          # Verify download was successful
+          if [ ! -s ./cc-test-reporter ]; then
+            echo "Download failed or file is empty."
+            exit 1
+          fi
+          echo "Code Climate test reporter downloaded successfully."
+
+      - name: Notify Code Climate before build
+        run: |
+          ./cc-test-reporter before-build
+
       - run: echo "Running tests with parallel execution and measuring coverage..."
       - name: Run tests with pytest and coverage
         run: |
           pytest --cov=./ --cov-report=xml --numprocesses=auto
+      
+      - name: Notify Code Climate after build
+        run: |
+          ./cc-test-reporter after-build
+
+      - name: Upload coverage to Code Climate
+        env:
+          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
+        run: |
+          ./cc-test-reporter upload-coverage
 
       - run: echo "Listing repository files after tests..."
       - name: List files in repository
@@ -50,28 +76,3 @@ jobs:
         with:
           name: coverage-report
           path: coverage.xml
-
-      - name: Download Code Climate test reporter
-        run: |
-          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
-          chmod +x ./cc-test-reporter
-          
-          # Verify download was successful
-          if [ ! -s ./cc-test-reporter ]; then
-            echo "Download failed or file is empty."
-            exit 1
-          fi
-          echo "Code Climate test reporter downloaded successfully."
-
-      - name: Upload coverage to Code Climate
-        env:
-          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
-        run: |
-          if [ -f coverage.xml ]; then
-            echo "Content of coverage.xml:"
-            cat coverage.xml
-          else
-            echo "coverage.xml not found."
-          fi
-          ./cc-test-reporter before-build
-          ./cc-test-reporter after-build
